{{- if .Values.apiService.create -}}
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: {{ .Values.apiService.insecureSkipTLSVerify }}
  service:
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
  version: v1beta1
  versionPriority: 100
{{- end -}}
