{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:{{ .Values.name }}
  labels:
    giantswarm.io/service-type: {{ .Values.serviceType }}
    app: {{ .Values.k8sAppLabel }}
rules:
  - apiGroups:
    - ""
    resources:
      - pods
      - nodes
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
    - ""
    resources:
    - nodes/stats
    verbs:
    - get
    - create
  - apiGroups:
    - extensions
    resources:
    - podsecuritypolicies
    verbs:
    - use
    resourceNames:
    - {{ .Values.name }}
{{- end -}}
