kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    giantswarm.io/service-type: "managed"
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.name }}
  ingress:
  - ports:
    - port: {{ .Values.port }}
      protocol: TCP
  egress:
  - to:
    {{ $privateSubnets := list "10.0.0.0/8" "172.16.0.0/12" "192.168.0.0/16" -}}
    {{ $privateSubnets = append $privateSubnets .Values.Installation.V1.Guest.IPAM.NetworkCIDR -}}
    {{ $privateSubnets = $privateSubnets | uniq -}}
    {{ range $index, $privateSubnet := $privateSubnets -}}
    - ipBlock:
        cidr: {{ $privateSubnet }}
    {{ end -}}
  policyTypes:
  - Egress
  - Ingress
