version: 2.1
orbs:
  architect: giantswarm/architect@0.2.0

workflows:
  version: 2
  build_e2e:
    jobs:
      - architect/push-to-app-catalog:
          name: "package and push metrics-server-app chart"
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "metrics-server-app"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
