version: 2.1
orbs:
  architect: giantswarm/architect@4.37.0

# external cluster is used because tests use
# docker cp.
# otherwise the kind cluster containers and the
# container of app-test-suite cannot work together
jobs:
  test:
    machine: true
    environment:
      KIND_VERSION: v0.11.1
      KUBERNETES_VERSION: v1.24.17
    steps:
      - checkout
      - run:
          name: Download kind
          command: |
            curl -sLo kind https://github.com/kubernetes-sigs/kind/releases/download/$KIND_VERSION/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/bin
      - run:
          name: Spin up cluster
          command: |
            kind create cluster --config tests/kind_config.yaml --kubeconfig kind.kube.config
      - architect/run-tests-with-ats:
          chart_archive_prefix: "metrics-server"
          app-test-suite_version: "v0.5.0"
          app-test-suite_container_tag: "0.5.0"
          additional_app-test-suite_flags: "--external-cluster-version $KUBERNETES_VERSION"

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          context: architect
          executor: "app-build-suite"
          name: push-to-default-app-catalog
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "metrics-server-app"
          persist_chart_archive: true
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          executor: "app-build-suite"
          name: push-to-control-plane-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "metrics-server-app"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - test:
          name: execute tests
          requires:
            - push-to-default-app-catalog
          filters:
            # Do not trigger the job on master branch or release tags.
            branches:
              ignore:
                - master
            tags:
              ignore: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-metrics-server-to-aws-app-collection
          app_name: "metrics-server-app"
          app_namespace: "kube-system"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: architect
          name: push-metrics-server-to-azure-app-collection
          app_name: "metrics-server-app"
          app_namespace: "kube-system"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-to-control-plane-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
