apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    giantswarm.io/service-type: {{ .Values.serviceType }}
    app: {{ .Values.k8sAppLabel }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: {{ .Values.port }}
  selector:
    app: {{ .Values.k8sAppLabel }}
