{{- if .Values.apiService.create -}}
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
  labels:
    giantswarm.io/service-type: {{ .Values.serviceType }}
    app: {{ .Values.k8sAppLabel }}
spec:
  service:
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
  group: metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: {{ .Values.apiService.insecureSkipTLSVerify }}
  groupPriorityMinimum: 100
  versionPriority: 100
{{- end -}}
